name-template: '$NEXT_PATCH_VERSION'
tag-template: '$NEXT_PATCH_VERSION'
categories:
  - title: 'Features'
    labels:
      - 'type: new feature'
      - 'type: enhancement'
  - title: 'Bug Fixes'
    labels:
      - 'type: bug'
      - 'bug'
  - title: 'Maintenance'
    label: 'type: refactor'
change-template: '- $TITLE (#$NUMBER)'
exclude-labels:
  - 'skip-changelog'
template: |
  ## Changes

  $CHANGES

  ## Contributors
  We'd like to thank all the contributors who worked on this release!

  $CONTRIBUTORS

