server:
  port: 8999
  address: 0.0.0.0

spring:
   main:
     allow-bean-definition-overriding: true
   profiles:
     active: dev
   redis:
     host: localhost
     password: 123456
     port: 6379
   influxdb:
        url: http://localhost:8086
        username: test
        password: test
        database: test
        retention-policy: autogen
        connect-timeout: 10
        read-timeout: 30
        write-timeout: 10
   zookeeper:
        url : localhost:2181
        sessionTimeout: 5000
        connectionTimeout : 2000
soul:
    bufferSize: 4096
    timeVerify:
       timeDelay : 10
       enabled: false
logging:
    level:
        root: info
        org.springframework.boot: info
        org.apache.ibatis: info
        org.dromara.soul.bonuspoint: info
        org.dromara.soul.lottery: debug
        org.dromara.soul: debug

    path: "./logs"
