# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: docker-publish

on:
  release:
    type: ["published"]

env:
  REGISTRY: ghcr.io
  REPOSITORY: ${{ github.repository }}
  TAG: ${{ github.ref_name }}

jobs:
  build:
    # pre-release or draft status don't trigger this job.
    # this job called if and only if pre-release -> release or release directly.
    if: "!github.event.release.prerelease && !github.event.release.draft"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set Skip Env Var
        uses: ./.github/actions/skip-ci

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        if: env.SKIP_CI != 'true'
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        if: env.SKIP_CI != 'true'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        if: env.SKIP_CI != 'true'

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
        if: env.SKIP_CI != 'true'

      - name: Cache Maven Repos
        if: env.SKIP_CI != 'true'
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - uses: actions/setup-java@v1
        if: env.SKIP_CI != 'true'
        with:
          java-version: 8
          
      - name: Build with Maven
        if: env.SKIP_CI != 'true'
        run: ./mvnw -B clean -Prelease -Dmaven.javadoc.skip=true -B -Drat.skip=true -Djacoco.skip=true -DskipITs -DskipTests package

      - name: Build and push(admin)
        uses: docker/build-push-action@v3
        if: env.SKIP_CI != 'true'
        with:
          context: ./shenyu-dist/shenyu-admin-dist
          build-args: APP_NAME=apache-shenyu-incubating-*-admin-bin
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.REPOSITORY }}/admin:latest
            ${{ env.REPOSITORY }}/admin:${{ env.TAG }}
            ${{ env.REGISTRY }}/${{ env.REPOSITORY }}/admin:latest
            ${{ env.REGISTRY }}/${{ env.REPOSITORY }}/admin:${{ env.TAG }}

      - name: Build and push(bootstrap)
        uses: docker/build-push-action@v3
        if: env.SKIP_CI != 'true'
        with:
          context: ./shenyu-dist/shenyu-bootstrap-dist
          build-args: APP_NAME=apache-shenyu-incubating-*-bootstrap-bin
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.REPOSITORY }}/bootstrap:latest
            ${{ env.REPOSITORY }}/bootstrap:${{ env.TAG }}
            ${{ env.REGISTRY }}/${{ env.REPOSITORY }}/bootstrap:latest
            ${{ env.REGISTRY }}/${{ env.REPOSITORY }}/bootstrap:${{ env.TAG }}
